spring.application.name=api
hgbrasil.api.scheme=https
hgbrasil.api.host=34.102.203.11.nip.io
hgbrasil.api.path=previsoes
hgbrasil.api.fields=only_results,temp,city_name,time,forecast,max,min,date
hgbrasil.api.array-limit=3